package com.edomex.kiliantRSP.dto.DescPlazasdto.DescPlazasPartes.Percepciones;

import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public record DescPlazasDatosPercepciones(
        String secuenciaPlaza,
        BigDecimal total,
        String per1,
        String per2,
        String per3,
        String per4,
        String per5,
        String per6,
        String per7,
        String per8,
        String per9,
        String per10,

        BigDecimal imp1,
        BigDecimal imp2,
        BigDecimal imp3,
        BigDecimal imp4,
        BigDecimal imp5,
        BigDecimal imp6,
        BigDecimal imp7,
        BigDecimal imp8,
        BigDecimal imp9,
        BigDecimal imp10,

        String per1A,
        String per2A,
        String per3A,
        String per4A,
        String per5A,
        String per6A,
        String per7A,
        String per8A,
        String per9A,
        String per10A,
        String per11A,
        String per12A,
        String per13A,
        String per14A,
        String per15A,
        String per16A,
        String per17A,
        String per18A,
        String per19A,
        String per20A,

        BigDecimal imp1A,
        BigDecimal imp2A,
        BigDecimal imp3A,
        BigDecimal imp4A,
        BigDecimal imp5A,
        BigDecimal imp6A,
        BigDecimal imp7A,
        BigDecimal imp8A,
        BigDecimal imp9A,
        BigDecimal imp10A,
        BigDecimal imp11A,
        BigDecimal imp12A,
        BigDecimal imp13A,
        BigDecimal imp14A,
        BigDecimal imp15A,
        BigDecimal imp16A,
        BigDecimal imp17A,
        BigDecimal imp18A,
        BigDecimal imp19A,
        BigDecimal imp20A,

        String per1B,
        String per2B,
        String per3B,
        String per4B,
        String per5B,
        String per6B,
        String per7B,
        String per8B,
        String per9B,
        String per10B,
        String per11B,
        String per12B,
        String per13B,
        String per14B,
        String per15B,
        String per16B,
        String per17B,
        String per18B,
        String per19B,
        String per20B,

        BigDecimal imp1B,
        BigDecimal imp2B,
        BigDecimal imp3B,
        BigDecimal imp4B,
        BigDecimal imp5B,
        BigDecimal imp6B,
        BigDecimal imp7B,
        BigDecimal imp8B,
        BigDecimal imp9B,
        BigDecimal imp10B,
        BigDecimal imp11B,
        BigDecimal imp12B,
        BigDecimal imp13B,
        BigDecimal imp14B,
        BigDecimal imp15B,
        BigDecimal imp16B,
        BigDecimal imp17B,
        BigDecimal imp18B,
        BigDecimal imp19B,
        BigDecimal imp20B

) {
}
