package com.edomex.kiliantRSP.dto.DescPlazasdto.DescPlazasPartes.Deducciones;

import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public record DescPlazasDatosDeducciones(
        String secuenciaPlaza,
        BigDecimal total,
        String ded1,
        String ded2,
        String ded3,
        String ded4,
        String ded5,
        String ded6,
        String ded7,
        String ded8,
        String ded9,
        String ded10,

        BigDecimal imp1,
        BigDecimal imp2,
        BigDecimal imp3,
        BigDecimal imp4,
        BigDecimal imp5,
        BigDecimal imp6,
        BigDecimal imp7,
        BigDecimal imp8,
        BigDecimal imp9,
        BigDecimal imp10,

        String ded1A,
        String ded2A,
        String ded3A,
        String ded4A,
        String ded5A,
        String ded6A,
        String ded7A,
        String ded8A,
        String ded9A,
        String ded10A,
        String ded11A,
        String ded12A,
        String ded13A,
        String ded14A,
        String ded15A,
        String ded16A,
        String ded17A,
        String ded18A,
        String ded19A,
        String ded20A,

        BigDecimal imp1A,
        BigDecimal imp2A,
        BigDecimal imp3A,
        BigDecimal imp4A,
        BigDecimal imp5A,
        BigDecimal imp6A,
        BigDecimal imp7A,
        BigDecimal imp8A,
        BigDecimal imp9A,
        BigDecimal imp10A,
        BigDecimal imp11A,
        BigDecimal imp12A,
        BigDecimal imp13A,
        BigDecimal imp14A,
        BigDecimal imp15A,
        BigDecimal imp16A,
        BigDecimal imp17A,
        BigDecimal imp18A,
        BigDecimal imp19A,
        BigDecimal imp20A,

        String ded1B,
        String ded2B,
        String ded3B,
        String ded4B,
        String ded5B,
        String ded6B,
        String ded7B,
        String ded8B,
        String ded9B,
        String ded10B,
        String ded11B,
        String ded12B,
        String ded13B,
        String ded14B,
        String ded15B,
        String ded16B,
        String ded17B,
        String ded18B,
        String ded19B,
        String ded20B,

        BigDecimal imp1B,
        BigDecimal imp2B,
        BigDecimal imp3B,
        BigDecimal imp4B,
        BigDecimal imp5B,
        BigDecimal imp6B,
        BigDecimal imp7B,
        BigDecimal imp8B,
        BigDecimal imp9B,
        BigDecimal imp10B,
        BigDecimal imp11B,
        BigDecimal imp12B,
        BigDecimal imp13B,
        BigDecimal imp14B,
        BigDecimal imp15B,
        BigDecimal imp16B,
        BigDecimal imp17B,
        BigDecimal imp18B,
        BigDecimal imp19B,
        BigDecimal imp20B

) {
}
